### ISSUE TITLE
NONE compression support

### ISSUE THREAD

**Issue by simonafield** [sapientcoder/CabMaker#11]
Hello,

I noticed when running the program, only LZX and MSZIP compression is provided in the dropdown, when NONE can be applied as well. Using makecab.exe, `/D var=value` will allow you to set [directives](https://ss64.com/nt/makecab-directives.html) for the CAB. For example, `makecab.exe /D Compress=OFF`, in the case of NONE compression.

Thanks.

**Comment by sapientcoder** [comment]
Support for "None" has been added.

**Comment by simonafield** [comment]
Thanks.
