### ISSUE TITLE
No .EXE file.

### ISSUE THREAD

**Issue by StuartB4** [sapientcoder/CabMaker#4]
I just read this on 
https://yieldreturnpost.wordpress.com/2016/06/22/free-tool-to-create-cab-file-from-folder

> CabMaker is available out on GitHub.
You can download the released version (zip file which contains the compiled EXE) or edit the source code and compile yourself if you wish.

I downloaded it and extracted it but there is no .exe file.
How do I complile the files that are there.
![untitled](https://user-images.githubusercontent.com/16980026/43317766-10a11180-9196-11e8-8aaf-dd104f943aee.jpg)

Thanks.
Stuart.

**Comment by sapientcoder** [comment]
It looks like you downloaded the source code (which GitHub also provides as a .zip file) and not the .zip file I created with the EXE.

From the [CabMaker project page](https://github.com/sapientcoder/CabMaker), look for the 4 links that appear above the code. The links are for commits, branches, releases, and contributors. Click the one that says  "[3 releases](https://github.com/sapientcoder/CabMaker/releases)."

In the latest release (CabMaker 1.2), you'll see three files listed. Two say "source code" (GitHub creates those automatically), and one says CabMaker-1.2.zip. Download CabMaker-1.2.zip. The EXE file is in there.

If you want to download and compile the source code yourself, you'll need Visual Studio for that. Microsoft provides a free "community edition" which you can download [here](https://visualstudio.microsoft.com/downloads/).

**Comment by StuartB4** [comment]
Ok, thats great. 
Thanks very much.
