### ISSUE TITLE
Screenshot of CabMaker GUI is broken

### ISSUE THREAD

**Issue by ltdeta** [sapientcoder/CabMaker#9]
link on page is broken
[Screenshot of CabMaker GUI for makecab.exe](https://camo.githubusercontent.com/140546a37e027f98e293b26bb8c42f5dce6821455e9ea4a7820a1ed9265c346d/68747470733a2f2f7969656c6472657475726e706f73742e66696c65732e776f726470726573732e636f6d2f323032322f30312f6361626d616b65722d76312e352e706e67)

**Comment by sapientcoder** [comment]
Fixed.
